name: Deploy to Azure Spring Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build with Maven
        run: mvn package -DskipTests
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set up Azure CLI
        uses: azure/CLI@v1
      - name: Deploy to Azure Spring Cloud
        run: |
          az spring app deploy \
            --resource-group springoneent \
            --service springoneent \
            --name springone \
            --builder springone \
            --artifact-path target/spring-petclinic-3.1.0-SNAPSHOT.jar
