name: Deploy to Azure Spring Apps

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'microsoft'
          cache: maven
      - name: Build with Maven
        run: mvn package -DskipTests
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy to Azure Spring Apps
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az spring app deploy \
              --resource-group ${{ env.RESOURCE_GROUP }} \
              --service ${{ env.SERVICE }} \
              --name ${{ env.APP_NAME }} \
              --builder ${{ env.BUILDER }} \
              --artifact-path target/spring-petclinic-3.1.0-SNAPSHOT.jar
        env:
          RESOURCE_GROUP: springoneent
          SERVICE: springoneent
          APP_NAME: springone
          BUILDER: springone