name: Deploy to Azure Spring Apps

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'microsoft'
          cache: maven
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-          
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Run tests
        run: mvn test
      - name: Store JAR file name
        run: echo "::set-output name=jar-file::$(ls target/*.jar)"
        id: jar-file
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy to Azure Spring Apps
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az spring app deploy \
              --resource-group ${{ env.RESOURCE_GROUP }} \
              --service ${{ env.SERVICE }} \
              --name ${{ env.APP_NAME }} \
              --builder ${{ env.BUILDER }} \
              --artifact-path ${{ steps.jar-file.outputs.jar-file }}
        env:
          RESOURCE_GROUP: springoneent
          SERVICE: springoneent
          APP_NAME: springone
          BUILDER: springone